### ISSUE TITLE
No license and no release, is it okay to use?

### ISSUE THREAD

**Issue by bitboxer** [TheRealReal/prismic-elixir#30]
Short question: this repo is public, has interesting code to me, but sadly has no release and no licence. 

Is this okay to use in other projects? Or is this public accidentally?

**Comment by ianagne** [comment]
Just added the MIT license. Have at it!

Of note, the example on the README.md looks like it may have been for an older version. The main interface to use the api is through [Prismic.documents/2](https://github.com/TheRealReal/prismic-elixir/blob/master/lib/prismic.ex#L47-L165)

For example, you might do something like this to get a single document by id:
```elixir
case Prismic.documents(%{id: "document_id"}) do
  {:ok, [document]} -> document
  _ -> {:error, "could not retrieve document}
end
```

Or something like this to get documents by predicate:
```elixir
alias Prismic.Predicate

predicates = [Predicate.at("document.type", "page")]

case Prismic.documents(predicates) do
  {:ok, [documents]} -> documents
  _ -> {:error, "could not retrieve documents}
end
```

**Comment by bitboxer** [comment]
Awesome. Thank you! There is an older PR that adds some rendering code. Are you still interested in adding that kind of stuff? I might want to take that stuff and enhance it with the elements that I need.

**Comment by ianagne** [comment]
I think we'll end up closing that PR. We've been generally avoiding bringing the view layer logic into the client library, as we found that even low level fields of the same type can have wildly different use-cases.
