### ISSUE TITLE
Define a render/HTML module and protocol

### ISSUE THREAD

**Issue by sudostack** [TheRealReal/prismic-elixir#6]
If we follow what the other Prismic SDK's provide out of the box, we should provide a way to render mark-up. 

We can absolve each fragment of rendering responsibilities by creating a module whose responsibility is to take a fragment struct and rendering safe HTML string with it.

Alternatively, we could also just implement the `Phoenix.HTML` protocol for each fragment :)

**Comment by newtrat** [comment]
I'm gonna close this issue because I think we've usually found that it's easier to specify the HTML structure in the caller. Prismic doesn't really dictate a presentation for the data you put in it, so I'm not sure it makes sense to impose one in our library, even if it's purely optional.
